name: 'GitHub Actions metrics to Datadog'
description: 'Send metrics of GitHub Actions to Datadog'
author: 'Yuya Takeyama'
branding:
  icon: 'bar-chart'
  color: 'purple'
inputs:
  github-token:
    required: false
    description: 'GitHub API token'
  datadog-api-key:
    required: true
    description: 'Datadog API key'
  enable-workflow-metrics:
    required: false
    description: 'Set "true" to send workflow metrics'
    default: 'false'
  enable-billing-metrics:
    required: false
    description: 'Set "true" to send User/Organization billing metrics'
    default: 'false'
  enable-repository-workflows-billing-metrics:
    required: false
    description: 'Set "true" to send Repository Workflows billing metrics'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
